version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:eu-west-1:075206908135:task-definition/task-defenitionpush:1"
        LoadBalancerInfo:
          ContainerName: "followerservice"
          ContainerPort: 80
