version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore FollowService/FollowerService.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output FollowService/FollowerService.csproj
  post_build:
    commands:
      - echo Test started on `date`
      - dotnet test .\FollowerService.sln
  
artifacts:
  files:
    - ./**/*
  base-directory: './build_output'
