version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore FollowService/FollowerService.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output FollowService/FollowerService.csproj
      - dotnet test -c Release .\FollowerService.sln --logger trx --results-directory ./testresults
reports:
    DotnetTestExamples:
        file-format: VisualStudioTrx
        files:
            - '**/*'
        base-directory: './testresults'
artifacts:
  files:
    - '**/*'
  base-directory: './build_output'
