version: '3.4'

services:
  followerservice:
    image: ${DOCKER_REGISTRY-}followerservice
    volumes:
    - ~/.aws/:/root/.aws:ro
    build:
      context: .
      dockerfile: FollowService/Dockerfile

